// Tool identifiers — kept in a standalone module so App, Toolbar and Canvas
// can share them without creating a circular import.
export const TOOLS = {
  SELECT: 'select',
  DIRECT_SELECT: 'directSelect',
  GROUP_SELECT: 'groupSelect',
  MAGIC_WAND: 'magicWand',
  LASSO: 'lasso',
  PEN: 'pen',
  ADD_ANCHOR: 'addAnchor',
  DELETE_ANCHOR: 'deleteAnchor',
  CONVERT_ANCHOR: 'convertAnchor',
  CURVATURE: 'curvature',
  PENCIL: 'pencil',
  SMOOTH: 'smooth',
  PATH_ERASER: 'pathEraser',
  JOIN: 'join',
  PAINTBRUSH: 'paintbrush',
  BLOB_BRUSH: 'blobBrush',
  SHAPER: 'shaper',
  ERASER: 'eraser',
  SCISSORS: 'scissors',
  KNIFE: 'knife',
  RECTANGULAR_GRID: 'rectangularGrid',
  POLAR_GRID: 'polarGrid',
  TEXT: 'text',
  VERTICAL_TEXT: 'verticalText',
  TOUCH_TYPE: 'touchType',
  RECTANGLE: 'rectangle',
  ELLIPSE: 'ellipse',
  POLYGON: 'polygon',
  STAR: 'star',
  FLARE: 'flare',
  LINE: 'line',
  ARC: 'arc',
  SPIRAL: 'spiral',
  HAND: 'hand',
  ROTATE_VIEW: 'rotateView',
  ZOOM: 'zoom',
};
